name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's Docker daemon..."
        eval $(minikube docker-env)

    - name: Build Frontend Docker Image
      run: |
        cd frontend
        docker build -t fast123456/scdP_frontend:latest .

    - name: Build Backend Docker Image
      run: |
        cd ../server
        docker build -t fast123456/scdP_backend:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Frontend Docker Image
      run: docker push fast123456/scdP_frontend:latest

    - name: Push Backend Docker Image
      run: docker push fast123456/scdP_backend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
